src/main/java/eu/slachta/pdp/model/bm/BourdonMobileTestInformation.java
package eu.slachta.pdp.model.bm;

import java.text.DateFormat;
import java.util.Date;

public class BourdonMobileTestInformation {
	private long testId;
	private String userId;
	private int imagesPerPage;
	private int timePerPage;
	private int pages;
	private long time;
	private int age;
	private int sex;
	private int educationLevel;
	private String note;
	private String resolution;
	private int dpi;
	private int orientation;
	private int cellSize;
	private int refImg1Id;
	private int refImg2Id;
	private int refImg3Id;
    
	public BourdonMobileTestInformation() {
    
	}
	
	public BourdonMobileTestInformation(long testId,
			String userId,
			int imagesPerPage,
			int timePerPage,
			int pages,
			long time,
			int age,
			int sex,
			int educationLevel,
			String note,
			String resolution,
			int dpi,
			int orientation,
			int cellSize,
			int refImg1Id,
			int refImg2Id,
			int refImg3Id) {
		this.testId=testId;
		this.userId=userId;
		this.imagesPerPage=imagesPerPage;
		this.timePerPage=timePerPage;
		this.pages=pages;
		this.time=time;
		this.age=age;
		this.sex=sex;
		this.educationLevel=educationLevel;
		this.note=note;
		this.resolution=resolution;
		this.dpi=dpi;
		this.orientation=orientation;
		this.cellSize=cellSize;
		this.refImg1Id=refImg1Id;
		this.refImg2Id=refImg2Id;
		this.refImg3Id=refImg3Id;
	}
	
	/**
	 * @return the testId
	 */
	public long getTestId() {
		return testId;
	}

	/**
	 * @param testId the testId to set
	 */
	public void setTestId(long testId) {
		this.testId = testId;
	}

	public int getImagesPerPage() {
		return imagesPerPage;
	}

	public void setImagesPerPage(int imagesPerPage) {
		this.imagesPerPage = imagesPerPage;
	}

	public int getTimePerPage() {
		return timePerPage;
	}

	public void setTimePerPage(int timePerPage) {
		this.timePerPage = timePerPage;
	}

	public int getPages() {
		return pages;
	}

	public void setPages(int pages) {
		this.pages = pages;
	}

	public void setTime(long curentDateandTime) {
		this.time=curentDateandTime;
	}
	
	public long getTime(){
		return this.time;
	}
	
	public String getDate(){
		return DateFormat.getDateTimeInstance().format(new Date(this.time));
	}

	/**
	 * @return the sex
	 */
	public int getSex() {
		return sex;
	}

	/**
	 * @param sex the sex to set
	 */
	public void setSex(int sex) {
		this.sex = sex;
	}

	/**
	 * @return the age
	 */
	public int getAge() {
		return age;
	}

	/**
	 * @param age the age to set
	 */
	public void setAge(int age) {
		this.age = age;
	}

	/**
	 * @return the educationLevel
	 */
	public int getEducationLevel() {
		return educationLevel;
	}

	/**
	 * @param educationLevel the educationLevel to set
	 */
	public void setEducationLevel(int educationLevel) {
		this.educationLevel = educationLevel;
	}

	/**
	 * @return the note
	 */
	public String getNote() {
		return note;
	}

	/**
	 * @param note the note to set
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/**
	 * @return the dpi
	 */
	public int getDpi() {
		return dpi;
	}

	/**
	 * @param dpi the dpi to set
	 */
	public void setDpi(int dpi) {
		this.dpi = dpi;
	}

	/**
	 * @return the resolution
	 */
	public String getResolution() {
		return resolution;
	}

	/**
	 * @param resolution the resolution to set
	 */
	public void setResolution(String resolution) {
		this.resolution = resolution;
	}

	/**
	 * @return the orientation
	 */
	public int getOrientation() {
		return orientation;
	}

	/**
	 * @param orientation the orientation to set
	 */
	public void setOrientation(int orientation) {
		this.orientation = orientation;
	}

	/**
	 * @return the cellSize
	 */
	public int getCellSize() {
		return cellSize;
	}

	/**
	 * @param cellSize the cellSize to set
	 */
	public void setCellSize(int cellSize) {
		this.cellSize = cellSize;
	}

	/**
	 * @return the user_id
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * @param userId the user_id to set
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * @return the refImg1Id
	 */
	public int getRefImg1Id() {
		return refImg1Id;
	}

	/**
	 * @param refImg1Id the refImg1Id to set
	 */
	public void setRefImg1Id(int refImg1Id) {
		this.refImg1Id = refImg1Id;
	}

	/**
	 * @return the refImg2Id
	 */
	public int getRefImg2Id() {
		return refImg2Id;
	}

	/**
	 * @param refImg2Id the refImg2Id to set
	 */
	public void setRefImg2Id(int refImg2Id) {
		this.refImg2Id = refImg2Id;
	}

	/**
	 * @return the refImg3Id
	 */
	public int getRefImg3Id() {
		return refImg3Id;
	}

	/**
	 * @param refImg3Id the refImg3Id to set
	 */
	public void setRefImg3Id(int refImg3Id) {
		this.refImg3Id = refImg3Id;
	}
}

src/main/java/eu/slachta/pdp/model/server/Bourdonnorm.java
package eu.slachta.pdp.model.server;

import java.io.Serializable;
import javax.persistence.*;


/**
 * The persistent class for the bourdonnorm database table.
 * 
 */
@Entity
@Table(name="bourdonnorm")
@NamedQuery(name="Bourdonnorm.findAll", query="SELECT b FROM Bourdonnorm b")
public class Bourdonnorm implements Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(unique=true, nullable=false)
	private int id;

	@Column(length=45)
	private String description;

	@Column(nullable=false)
	private double iqr;

	@Column(nullable=false)
	private double lowerQuartile;

	@Column(nullable=false)
	private double maximum;

	@Column(nullable=false)
	private double mean;

	@Column(nullable=false)
	private double median;

	@Column(nullable=false)
	private double minimum;

	@Column(unique=true, nullable=false, length=45)
	private String name;

	@Column(nullable=false)
	private int numberOfSamples;

	@Column(nullable=false)
	private double upperQuartile;

	public Bourdonnorm() {
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public double getIqr() {
		return this.iqr;
	}

	public void setIqr(double iqr) {
		this.iqr = iqr;
	}

	public double getLowerQuartile() {
		return this.lowerQuartile;
	}

	public void setLowerQuartile(double lowerQuartile) {
		this.lowerQuartile = lowerQuartile;
	}

	public double getMaximum() {
		return this.maximum;
	}

	public void setMaximum(double maximum) {
		this.maximum = maximum;
	}

	public double getMean() {
		return this.mean;
	}

	public void setMean(double mean) {
		this.mean = mean;
	}

	public double getMedian() {
		return this.median;
	}

	public void setMedian(double median) {
		this.median = median;
	}

	public double getMinimum() {
		return this.minimum;
	}

	public void setMinimum(double minimum) {
		this.minimum = minimum;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getNumberOfSamples() {
		return this.numberOfSamples;
	}

	public void setNumberOfSamples(int numberOfSamples) {
		this.numberOfSamples = numberOfSamples;
	}

	public double getUpperQuartile() {
		return this.upperQuartile;
	}

	public void setUpperQuartile(double upperQuartile) {
		this.upperQuartile = upperQuartile;
	}

}

src/main/java/eu/slachta/pdp/model/server/Respondent.java
package eu.slachta.pdp.model.server;

import java.io.Serializable;
import javax.persistence.*;
import java.util.List;


/**
 * The persistent class for the respondent database table.
 * 
 */
@Entity
@Table(name="respondent")
@NamedQuery(name="Respondent.findAll", query="SELECT r FROM Respondent r")
public class Respondent implements Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(unique=true, nullable=false)
	private int id;

	@Column(nullable=false)
	private int age;

	@Column(nullable=false)
	private int educationLevel;

	@Column(nullable=false, length=45)
	private String name;

	@Column(nullable=false, length=19)
	private String respondentKey;

	@Column(nullable=false)
	private int sex;

	@Column(nullable=false, length=45)
	private String surname;

	//bi-directional many-to-one association to Bourdontest
	@OneToMany(mappedBy="respondent")
	private List<Bourdontest> bourdontests;

	public Respondent() {
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public int getEducationLevel() {
		return this.educationLevel;
	}

	public void setEducationLevel(int educationLevel) {
		this.educationLevel = educationLevel;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRespondentKey() {
		return this.respondentKey;
	}

	public void setRespondentKey(String respondentKey) {
		this.respondentKey = respondentKey;
	}

	public int getSex() {
		return this.sex;
	}

	public void setSex(int sex) {
		this.sex = sex;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public List<Bourdontest> getBourdontests() {
		return this.bourdontests;
	}

	public void setBourdontests(List<Bourdontest> bourdontests) {
		this.bourdontests = bourdontests;
	}

	public Bourdontest addBourdontest(Bourdontest bourdontest) {
		getBourdontests().add(bourdontest);
		bourdontest.setRespondent(this);

		return bourdontest;
	}

	public Bourdontest removeBourdontest(Bourdontest bourdontest) {
		getBourdontests().remove(bourdontest);
		bourdontest.setRespondent(null);

		return bourdontest;
	}

}

src/main/java/eu/slachta/pdp/controller/LoginController.java
package eu.slachta.pdp.controller;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

@Controller
public class LoginController {
	
	@RequestMapping("/")
	public String index(Model model) {
		return "redirect:/login";
	}
 
	@RequestMapping(value = { "login" }, method = { RequestMethod.GET })
	public String login(
			ModelMap model, 
			@RequestParam(value="authfailed", required=false) Boolean authfailed
			) 
	{
		if(authfailed!=null){
			model.addAttribute("authfailed", authfailed);			
		}
 
		return "login";
	}
 
	@RequestMapping(value="/logout", method = RequestMethod.GET)
	public String logout(ModelMap model) {
 
		return "login";
	}
}

src/main/java/eu/slachta/pdp/controller/RespondentController.java
package eu.slachta.pdp.controller;

import java.security.Principal;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.Resource;
import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import eu.slachta.pdp.form.NewRespondentForm;
import eu.slachta.pdp.model.server.Bourdontest;
import eu.slachta.pdp.model.server.Respondent;
import eu.slachta.pdp.service.BourdonTestPageService;
import eu.slachta.pdp.service.BourdonTestService;
import eu.slachta.pdp.service.RespondentService;
import eu.slachta.pdp.service.TestTypeService;

@Controller
public class RespondentController {
	private static final Logger logger = LoggerFactory.getLogger(RespondentController.class);

	@Resource(name = "bourdonTestPageService")
	private BourdonTestPageService bourdonTestPageService;

	@Resource(name = "bourdonTestService")
	private BourdonTestService bourdonTestService;

	@Resource(name = "respondentService")
	private RespondentService respondentService;
	
	@Resource(name = "testTypeService")
	private TestTypeService testtypeService;
	
	@RequestMapping(value = "/respondent", method = RequestMethod.GET)
	public String redir(ModelMap model, Principal principal) {
		return "redirect:/respondent/all";
	}
	
	@RequestMapping(value = "/respondent/all", method = RequestMethod.GET)
	public String printListOfAllTests(ModelMap model, Principal principal) {
		List<Respondent> r = respondentService.findAll();

		model.addAttribute("respondents", r);
		return "respondentsAll";
	}

	@RequestMapping("/respondent/{id}")
	public String getTest(@PathVariable Integer id, ModelMap model) {
		Respondent r = respondentService.findById(id);
		model.addAttribute("respondent", r);
		
		List<Bourdontest> bt = bourdonTestService.findTestsByRespondentId(id);
		model.addAttribute("tests", bt);
		
		return "respondent";
	}
	
	@RequestMapping("/respondent/delete/{id}")
	public String deleteTest(@PathVariable Integer id, ModelMap model) {
		Respondent r = respondentService.findById(id);
		
		if(r != null){
			respondentService.deleteRespondent(id);
			
			List<Respondent> lr = respondentService.findAll();

			model.addAttribute("respondents", lr);
			model.addAttribute("id", id);
		}else{
			List<Respondent> lr = respondentService.findAll();

			model.addAttribute("respondents", lr);
			model.addAttribute("id", id);
		}

		return "respondentsAll";
	}
	
	@RequestMapping(value="/respondent/delete/{id}/deleteTest/{testId}")
	public String deleteRespondentsTest(@PathVariable Integer id, @PathVariable Integer testId, ModelMap model) {
		bourdonTestService.delete(testId);
		
		List<Bourdontest> bt = bourdonTestService.findTestsByRespondentId(id);
		model.addAttribute("tests", bt);
		
		Respondent r = respondentService.findById(id);
		model.addAttribute("respondent", r);

		return "respondentsAll";
	}
	
	@RequestMapping(value="/respondent/search")
	public String search(ModelMap model) {

		return "respondentsAll";
	}
	
	@RequestMapping(value="/respondent/add", method = RequestMethod.GET)
	public String getRespondentAdditionForm(
			ModelMap model, 
			@RequestParam(value="exists", required=false) Boolean exists, 
			@RequestParam(value="notValidUserKey", required=false) Boolean notValidUserKey
			) 
	{
		Map<Integer, String > sex = new HashMap<Integer, String>();
		sex.put(0, "Muž");
		sex.put(1, "Žena");

		model.addAttribute("sex", sex);
		
		Map<Integer, String > educationLevel = new HashMap<Integer, String>();
		educationLevel.put(0, "Základní vzdělání");
		educationLevel.put(1, "Střední vzdělání s výučním listem");
		educationLevel.put(2, "Střední vzdělání s maturitní zkouškou");
		educationLevel.put(3, "Vyšší odborné vzdělání nebo vysokoškolské vzdělání - bakalářský program");
		educationLevel.put(4, "Vysokoškolské vzdělání - magisterský program");
		educationLevel.put(5, "Vysokoškolské vzdělání - doktorský program");

		model.addAttribute("educationLevel", educationLevel);
		model.addAttribute("formData", new NewRespondentForm());
		model.addAttribute("exists", exists);
		model.addAttribute("notValidUserKey", notValidUserKey);	
		
		return "respondentAddForm";
	}
	
	@RequestMapping(value="/respondent/add", method = RequestMethod.POST)
	public String getRespondentAdd(ModelMap model, @Valid NewRespondentForm form) {
		if(isUserKeyValid(form.getRespondentKey())){
			if(form.getRespondentKey().equals("0000-0000-0000-0000")){
				logger.info("Respondent added");
				Respondent respondent = new Respondent();
				respondent.setAge(form.getAge());
				respondent.setEducationLevel(form.getEducationLevel());
				respondent.setName(form.getName());
				model.addAttribute("name", form.getName());
				respondent.setRespondentKey(form.getRespondentKey());
				respondent.setSex(form.getSex());
				respondent.setSurname(form.getSurname());
				respondentService.createRespondent(respondent);
			}else{
				if(respondentService.findByRespondentKey(form.getRespondentKey()).size()==0){
					logger.info("Respondent added");
					Respondent respondent = new Respondent();
					respondent.setAge(form.getAge());
					respondent.setEducationLevel(form.getEducationLevel());
					model.addAttribute("name", form.getName());
					respondent.setName(form.getName());
					respondent.setRespondentKey(form.getRespondentKey());
					respondent.setSex(form.getSex());
					respondent.setSurname(form.getSurname());
					respondentService.createRespondent(respondent);
				}else{
					logger.info("Respondent exists");
					model.addAttribute("exists", true);
					return "redirect:/respondent/add";
				}
			}
		}else{
			model.addAttribute("notValidUserKey", true);
			return "redirect:/respondent/add";
		}
		
		
		return "redirect:/respondent/all";
	}
	
	public static boolean isUserKeyValid(String userKey){
		return userKey.matches("^([A-Z0-9]{4})-([A-Z0-9]{4})-([A-Z0-9]{4})-([A-Z0-9]{4})");
	}
	
}

src/main/java/eu/slachta/pdp/controller/ResultsController.java
package eu.slachta.pdp.controller;

import java.security.Principal;

import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Controller
public class ResultsController {
	
	@RequestMapping(value="/results", method = RequestMethod.GET)
	public String printTypesOfTests(ModelMap model, Principal principal) {
		return "results";
	}
}

src/main/webapp/WEB-INF/views/bourdonAllTests.jsp
<%@ page pageEncoding="UTF-8" language="java"
	contentType="text/html; charset=UTF-8"%>
<%@ include file="/WEB-INF/layout/header.jsp"%>

<div class="row row-offcanvas row-offcanvas-right">
	<div class="col-xs-12 col-sm-9">
		<div class="panel panel-default">
			<!-- Default panel contents -->
			<div class="panel-heading">Seznam Bourdonových testů</div>
			<!-- Table -->
			<c:if test="${not empty tests}">
				<table class="table table-hover">
					<thead>
						<tr>
							<th>ID testu</th>
							<th>Respondent</th>
							<th>API klíč</th>
							<th>Datum testu</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<c:forEach items="${tests}" var="test">
							<tr>
								<td>${fn:escapeXml(test.id)}</td>
								<td>${fn:escapeXml(test.respondent.id)}</td>
								<td>${fn:escapeXml(fn:substring(test.apiKey,0,20))}...</td>
								<td>${fn:escapeXml(test.date)}</td>
								<td><a
									href="${pageContext.request.contextPath}/results/${fn:escapeXml(test.testtype.prefix)}/test/${fn:escapeXml(test.id)}"
									class="btn btn-primary btn-xs">Zobrazit test</a> 
									<a
									href="${pageContext.request.contextPath}/results/${fn:escapeXml(test.testtype.prefix)}/delete/${fn:escapeXml(test.id)}"
									class="btn btn-danger btn-xs">Smazat test</a></td>
							</tr>
						</c:forEach>
				</table>
			</c:if>
			<c:if test="${empty tests}">
				<div class="panel-body">
					<p>Testy nenalezeny.</p>
				</div>
			</c:if>
		</div>
	</div>
	<!--/span-->
	<!--/span-->
	<div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar"
		role="navigation">
		<div class="panel panel-default">
			<!-- Default panel contents -->
			<div class="panel-heading">Bourdonův test</div>
			<nav class="nav-sidebar">
				<ul class="nav">
					<li><a
						href="${pageContext.request.contextPath}/results/bourdon/all">Všechny
							testy</a></li>
					<li><a href="#">Hledání testů</a></li>
				</ul>
			</nav>
		</div>
	</div>
	<!--/span-->
</div>


<%@include file="/WEB-INF/layout/footer.jsp"%>

src/main/webapp/WEB-INF/views/bourdonOverview.jsp
<%@ page pageEncoding="UTF-8" language="java"
	contentType="text/html; charset=UTF-8"%>
<%@ include file="/WEB-INF/layout/header.jsp"%>

<div class="row row-offcanvas row-offcanvas-right">
	<div class="col-xs-12 col-sm-9">
		<div class="panel panel-default">
			<!-- Default panel contents -->
			<div class="panel-heading">Sumarizovaná data</div>

			<div class="panel-body">
				<dl class="dl-horizontal">
					<dt>Počet testů:</dt>
					<dd>${fn:escapeXml(numberOfTests)}</dd>
					<dt>Property 1:</dt>
					<dd>Value 1</dd>
					<dt>Property 2:</dt>
					<dd>Value 2</dd>
					<dt>Property 3:</dt>
					<dd>Value 3</dd>
				</dl>
			</div>
		</div>

		<div class="panel panel-default">
			<!-- Default panel contents -->
			<div class="panel-heading">Posledních 15 testů</div>
			<div class="panel-body">
				<p>Tato tabulka obsahuje naposledy přidané testy do databáze.</p>
			</div>

			<c:if test="${not empty tests}">
				<table class="table table-hover row-clickable">
					<thead>
						<tr>
							<th>ID testu</th>
							<th>Respondent</th>
							<th>API klíč</th>
							<th>Datum testu</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<c:forEach items="${tests}" var="test">
							<tr>
								<td>${fn:escapeXml(test.id)}</td>
								<td>${fn:escapeXml(test.respondent.id)}</td>
								<td>${fn:escapeXml(fn:substring(test.apiKey,0,20))}...</td>
								<td>${fn:escapeXml(test.date)}</td>
								<td><a
									href="${pageContext.request.contextPath}/results/bourdon/test/${fn:escapeXml(test.id)}"
									class="btn btn-primary btn-xs">Zobrazit test</a></td>
							</tr>
						</c:forEach>
				</table>
			</c:if>
			<c:if test="${empty tests}">
				<div class="panel-body">
					<p>Testy nenalezeny.</p>
				</div>
			</c:if>
		</div>
	</div>

	<!--/span-->
	<div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar"
		role="navigation">
		<div class="panel panel-default">
			<!-- Default panel contents -->
			<div class="panel-heading">Bourdonův test</div>
			<nav class="nav-sidebar">
				<ul class="nav">
					<li><a
						href="${pageContext.request.contextPath}/results/bourdon/overview">Přehled
							a informace o testech</a></li>
					<li><a
						href="${pageContext.request.contextPath}/results/bourdon/all">Všechny
							testy</a></li>
					<li><a href="#">Hledání testů</a></li>
				</ul>
			</nav>
		</div>
	</div>
	<!--/span-->
</div>

<%@include file="/WEB-INF/layout/footer.jsp"%>

src/main/webapp/WEB-INF/views/bourdonStatsList.jsp
<%@ page pageEncoding="UTF-8" language="java"
	contentType="text/html; charset=UTF-8"%>
<%@ include file="/WEB-INF/layout/header.jsp"%>

<div class="panel panel-default">
	<!-- Default panel contents -->
	<div class="panel-heading">Seznam testů pro exploratorní analýzu</div>
	<!-- Table -->
	<c:if test="${not empty tests}">
		<div class="panel-body">
			<form:form action="${pageContext.request.contextPath}/statistics/bourdon/multipleexploratory" method="POST" commandName="bourdonStatsTestChoices">
				<table class="table table-hover">
					<thead>
						<tr>
							<th></th>
							<th>ID testu</th>
							<th>Respondent</th>
							<th>API klíč</th>
							<th>Datum testu</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<c:forEach items="${tests}" var="test">
							<tr>
								<td><form:checkbox path="ids" value="${fn:escapeXml(test.id)}" /></td>
								<td>${fn:escapeXml(test.id)}</td>
								<td>${fn:escapeXml(test.respondent.id)}</td>
								<td>${fn:escapeXml(fn:substring(test.apiKey,0,20))}...</td>
								<td>${fn:escapeXml(test.date)}</td>
								<td><a
									href="${pageContext.request.contextPath}/statistics/${fn:escapeXml(test.testtype.prefix)}/exploratory/${fn:escapeXml(test.id)}"
									class="btn btn-primary btn-xs">Exploratorní analýza</a></td>
							</tr>
						</c:forEach>
				</table>
				<div class="panel-footer">
					<button type="submit" class="btn btn-default" name="action" value="compare">Srovnání exploratorních analýz testů</button>
					<button type="submit" class="btn btn-default" name="action" value="norm">Stanovit normu z výběru testů</button>
					<button type="submit" class="btn btn-default" name="action" value="allnorm">Stanovit normu ze všech testů</button>
				</div>
			</form:form>
		</div>
	</c:if>
	<c:if test="${empty tests}">
		<div class="panel-body">
			<p>Testy nenalezeny.</p>
		</div>
	</c:if>
</div>


<%@include file="/WEB-INF/layout/footer.jsp"%>

src/main/webapp/WEB-INF/views/results.jsp
<%@ page pageEncoding="UTF-8" language="java"
	contentType="text/html; charset=UTF-8"%>
<%@ include file="/WEB-INF/layout/header.jsp"%>

<div class="panel panel-default">
	<div class="panel-body">
		<div class="row">
			<div class="col-sm-6 col-md-4">
				<div class="thumbnail">
					<img
						src="${pageContext.request.contextPath}/resources/img/bourdon.png"
						alt="Bourdonův test">
					<div class="caption">
						<h3>Bourdonův test</h3>
						<p>Ve všech modifikacích Bourdonova testu se v zásadě jedná o
							řady navzájem si velice podobných symbolů mezi nimiž má proband
							za úkol diferencovat v průběhu delšího přesně stanoveného času.
							Jedná se o neverbální výkonový test, který neklade žádné nároky
							na jazykové znalosti nebo na zvláštní vědomosti.</p>
						<p>
							<a href="${pageContext.request.contextPath}/results/bourdon"
								class="btn btn-primary" role="button">Prohlížet data testů</a>
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>

</div>

<%@include file="/WEB-INF/layout/footer.jsp"%>